name: 'warn if outside of'
description: 'Comment a notice if the change set contains a file which is not supposed to be changed'
inputs:
  if_contains:
    description: 'If the change set contains "if_contains" regex'
    required: true
  warns:
    description: 'Warn if the change set contains a file which matches "warns" regex. Can have multiple regex separated by ",".'
    required: true
  except:
    description: 'Except thw files matches except regex. Can have multiple regex separated by ",".'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/index.js'
