name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  if_contains:
    description: 'If the change set contains this pattern'
    required: true
  should_not_contain:
    description: 'Warn if the change set contains a file which matches this pattern'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/hello.js'
