name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  if_contains:
    description: 'If the change set contains "if_contains" pattern'
    required: true
  warns:
    description: 'Warn if the change set contains a file which matches "warns" pattern'
    required: true
  except: 'Cartfile'
    description: 'Except thw files matches except pattern'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/hello.js'
