name: hello

on:
  push:
    paths:
      - 'src/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get assignee from github payload
        id: get-assignee
        uses: ku/whistle
