name: hello
on:
  push:
    paths:
      - 'src/**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get assignee from github payload
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        id: get-assignee
        uses: ku/whistle@master
        with:
          if_contains: 'src/'
          warns: '!src/'
          except: 'Cartfile'
