name: hello

on:
  pull_request:
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: node src/hello.js
