name: hello
on:
  pull_request:
    paths:
      - 'src/**'
  push:
    paths:
      - 'src/**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get assignee from github payload
        id: get-assignee
        uses: ku/whistle@master
        with:
          if_contains: 'src/'
          warns: '!src/'
          except: 'Cartfile'
