name: hello

on:
  push:
    paths:
      - 'src/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: find ../..
        using: 'node12'
        main: 'src/hello.js'
